Add services section with mysql
The builds are currently failing due to mysql connection errors:

```
mysqladmin: connect to server at 'localhost' failed

error: 'Can't connect to MySQL server on 'localhost' (111)'

Check that mysqld is running on localhost and that the port is 3306.

You can check this by doing 'telnet localhost 3306'
```

Looks like we need to instruct travis to start the mysql service. Via https://docs.travis-ci.com/user/database-setup/