Fix failing travis builds (#53)
* Add services section with mysql

The builds are currently failing due to mysql connection errors:

```
mysqladmin: connect to server at 'localhost' failed

error: 'Can't connect to MySQL server on 'localhost' (111)'

Check that mysqld is running on localhost and that the port is 3306.

You can check this by doing 'telnet localhost 3306'
```

Looks like we need to instruct travis to start the mysql service. Via https://docs.travis-ci.com/user/database-setup/

* Bounce the PHP version to 7.2

The build is failing on 7.0 due to not being supported by phpunit. Let's use PHP 7.2 instead.

* Actually bounce the PHP version to 7.2

* Lock to PHPunit v7.x for PHP 7.2

This also changes the notation for required version for PHP 5.6

* Change the composer global require notation

* Run the ./vendor/bin/phpunit instead of phpunit

* Prepend the ./vendor with $HOME

* Use just the vendor/bin/phpunit script

* Do not override $PATH

Per https://docs.travis-ci.com/user/languages/php/#default-build-script

* Do not override the default script

Travis should use phpunit by default. Per https://docs.travis-ci.com/user/languages/php/#default-build-script

* Export more paths